# -*- coding: utf-8 -*-
"""generetor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fjOSNDJvRJg7ejX1QKpBMAeutUom8G64
"""

import random
uppers = [chr(random.randint(65,90)) for i in range(5)] # list comprehantion içinde random olarak 3 tane büyük harf üretecek
lowers = [chr(random.randint(97,122)) for i in range(5)] # list comprehantion içinde random olarak 3 tane küçük harf üretecek
numbers = [chr(random.randint(48,57)) for i in range(5)] # list comprehantion içinde random olarak 3 tane rakam üretecek
chars = [chr(random.randint(33,47)) + chr(random.randint(58,64))] # list comprehantion içinde random olarak 2 tane özel karakter üretecek

passw = "".join(uppers) + "".join(lowers) + "".join(numbers) + "".join(chars)

def karıştır(password) : 
    templist = list(password)
    random.shuffle(templist)
    return "".join(templist)

print(karıştır(passw))